services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./src:/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro                # Main NGINX config
      - ./nginx/api_key_map.conf:/etc/nginx/conf.d/api_key_map.conf:ro  # API key map
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro    # Default server config
    depends_on:
      - fastapi-app
