version: '3.9'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - .env  # Reference the .env file
    volumes:
      - ./src:/app  # Mount the source code directory for development
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
